### ISSUE TITLE
Hello, I shouldn't bother you. I want to learn how to get a device tree. Can you teach me? I would like you to have a coffee.

### ISSUE THREAD

**Issue by 58773622** [Ramisky/device_xiaomi_apollon#2]
Hello, I shouldn't bother you. I want to learn how to get a device tree. Can you teach me? I would like you to have a coffee.

**Comment by ahmedtohamy1** [comment]
@58773622 Wtaf

**Comment by przekichane** [comment]
🤨

**Comment by 58773622** [comment]
I want to learn about android with you, such as writing a twrp device tree,

**Comment by przekichane** [comment]
its probably much harder than you are thinking

**Comment by 58773622** [comment]
I'm reading the relevant documents myself. I'm not very good at decrypting FBE. Do you have wechat in China? We add a friend. I'm willing to pay for knowledge

**Comment by Ramisky** [comment]
Isn't really an issue, someone is asking for paid lessons?
