### ISSUE TITLE
hey there just report a bug

### ISSUE THREAD

**Issue by judywang015** [Ramisky/device_xiaomi_apollon#3]
Sorry to interrupt you, but there's an annoying bug to the system. I'm using a redmi k30s ultra with lineage OS 20. Sometimes when playing music with Apple Music, there's a bit glitch once in a while and it's especially frequent when playing a song that hasn't been cached. It doesn't happen on other music or stream apps. It's driving me crazy and I just wanna let you know. Thanks for your work btw.

**Comment by Ramisky** [comment]
I know it's closed, but I'm intrigued as to if it's fixed? I do suspect it's an app issue anyways but please do tell me

**Comment by judywang015** [comment]
@Ramisky hello thanks for your response. I close the issue because I don't think it's the right place to report bugs. I summit the problem right there. https://gitlab.com/LineageOS/issues/android/-/issues/6238 
Also I've guessed that it could be app bug, not system bug. Or maybe my device's broken. I've no idea.
